#  the pages job run in the deploy stage; the job affect branch of master;
#  the test job runs in the test stage； builds the site in a directory called test； The job affects all branches except master

before_script:
  - npm install --registry=http://registry.npm.release.ctripcorp.com --no-package-lock
  - npm run father doc build
cache:
  paths:
    - node_modules/

test:
  stage: test
  image: hub.cloud.ctripcorp.com/baseimage/node:8
  script:
    - mv .doc test
  artifacts:
    paths:
      - test
  except:
    - master


pages:
  stage: deploy
  image: hub.cloud.ctripcorp.com/baseimage/node:8
  script:
    - mv .doc public
  artifacts:
    paths:
      - public
  only:
    - master

